# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='nlp-cooking',
    version='0.1.0',
    python_requires='==3.*,>=3.7.0',
    packages=[
        'nlp_cooking', 'nlp_cooking.normalize', 'nlp_cooking.tokenizer',
        'nlp_cooking.tokenizer.ja'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=['emoji==0.*,>=0.6.0', 'fasttext', 'loguru==0.*,>=0.5.3'],
    dependency_links=[
        'git+https://github.com/facebookresearch/fastText.git#egg=fasttext'
    ],
    extras_require={
        "dev": ["jedi==0.17.2", "jupyter==1.*,>=1.0.0"],
        "ja": [
            "mecab-python3==1.*,>=1.0.3", "neologdn==0.*,>=0.4.0",
            "sudachidict-full==20201223.*,>=20201223.0.0",
            "sudachipy==0.*,>=0.5.1"
        ]
    },
)
